#
# Memory options
#

- name: Disable swapiness
  sysctl: name=vm.swappiness value=0 state=present reload=yes
  tags:
  - memory

- name: VM Min free kbytes
  sysctl: name=vm.min_free_kbytes value=524288 state=present reload=yes
  tags:
  - memory

- name: VM VFS Cache Pressure
  sysctl: name=vm.vfs_cache_pressure value=50 state=present reload=yes
  tags:
  - memory

- name: Disable NUMA
  shell: echo "0" | sudo tee /proc/sys/vm/zone_reclaim_mode
  tags:
  - memory

- name: Disable huge pages
  shell: echo "never" | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
  tags:
  - memory

- name: Change dirty pages ratio
  sysctl: name=vm.dirty_background_ratio value=3 state=present reload=yes
  tags:
  - memory

- name: Data dirty ratio
  sysctl: name=vm.dirty_ratio value=15 state=present reload=yes
  tags:
  - memory
